apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: j4vnrv0v9-python-gitops
  description: This is GitOps manifest for j4vnrv0v9-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=j4vnrv0v9-python
    backstage.io/kubernetes-id: j4vnrv0v9-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: j4vnrv0v9-python   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:j4vnrv0v9-python
